### PR TITLE
Add method returning events directly

### PR DESCRIPTION
**Pull request by dr-orlovsky**
When the user processes all events after poll without queuing them it makes sense to use a dedicated API returning `Result` with events object

### CODE REVIEW

**Comment by cloudhead** [comment]
This will allocate a new events vector everytime the loop is woken up; not sure it's a good idea.

**Comment by dr-orlovsky** [comment]
Such allocation happens anyway in the call to `initialize` at the beginning of the `wait_timeout` method

**Comment by dr-orlovsky** [comment]
The unnecessary allocation actually solved in subsequent PR #11

**Comment by cloudhead** [comment]
You're right, ok great; it should be avoided if possible.

**Comment by cloudhead** [comment]
Closed in favor of #12

**Pull request closed without merging**
