### PR TITLE
API refactoring

### PR DESCRIPTION
**Pull request by dr-orlovsky**
Based on #10 and other PRs, sumarising them.

On top it simplifies two types (`Sources` and `Events`) into a single workflow with `Poll::wait(_timeout)` function.

This removes allocation at the beginning of each call which was happened in `Events::initialize`.

### CODE REVIEW

**Comment by cloudhead** [comment]
I like some of this, but not so much the combining of `Poll` with `Events`, as it hides the fact that certain operations can clear the events list, and makes the API a little awkard (`!poll.has_events()` vs. `events.is_empty()`).

**Comment by dr-orlovsky** [comment]
Yes, I was not also that happy about the combination, however I explored probably any other way and there is no other option for avoiding unnecessary allocations. 

The fact is the cleaning of the event log has been present before and was even less obvious (if you call `wait_timeout` with `events`, it clears the iterator and cancels all previously unread events). Here I just made it documented.

**Comment by cloudhead** [comment]
Hmm perhaps worth looking at how https://docs.rs/polling/latest/polling/ does it.

**Comment by dr-orlovsky** [comment]
It does it very differently. First, the events there are list of events, not sources with event flags. And it just extends the once allocated vec with new events. It also uses mutex locks.

**Comment by dr-orlovsky** [comment]
I.e. if we do as in `polling`, existing tests will fail (since they rely on the fact that the log is cleared on each call to the `wait_timeout`)

**Comment by cloudhead** [comment]
Ok, I will try to look into it as well. I'm starting an integration branch to pull in your changes one by one.

**Comment by cloudhead** [comment]
Closed in favor of #12

**Pull request closed without merging**
